version: "3.8"

services:
  db:
      image: postgres:13.3-alpine
      restart: always
      environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=secret
          - POSTGRES_DB=postgres
          - APP_DB_USER=se_db_user
          - APP_DB_PASS=se_db_secret
          - APP_DB_NAME=se_db
          - PGDATA=/Backend/postgresql/data
      container_name: postgres_db
      volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./data/production:/var/lib/postgresql/data
      ports:
      - "5432:5432"

  backend:
    container_name: "backend"
    build: .
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:5000:8000"
    depends_on:
      - db
