# Generated by Django 3.1.3 on 2021-11-03 23:22

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('thumbnail_size', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'size must be bigger than 0')])),
                ('storage_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('S3', 'S3'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=16)),
                ('content_type', models.CharField(max_length=255)),
                ('directory', models.CharField(blank=True, choices=[('AVATAR', 'Avatar'), ('CHALLENGE', 'Challenge'), ('EVENT', 'Event'), ('ARTICLE', 'Article'), ('QUESTION', 'Question'), ('ANSWER', 'Answer'), ('EMAIL', 'Email')], max_length=128, null=True)),
                ('access_url', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('deleted', models.BooleanField(default=False)),
                ('digest', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
