# Generated by Django 3.1.3 on 2021-09-18 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('thumbnail_size', models.BigIntegerField(blank=True, null=True)),
                ('size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=256)),
                ('store_type', models.CharField(max_length=256)),
                ('directory', models.TextField(null=True)),
                ('access_url', models.TextField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('digest', models.CharField(max_length=128)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_file',
            },
        ),
    ]
