# Generated by Django 3.1.3 on 2021-09-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='access_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='directory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
