# Generated by Django 3.1.3 on 2021-11-04 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
        ('media_file', '0002_media_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_table', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_table', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantbanner',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_restaurant_banner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantbanner',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_restaurant_banner', to='media_file.media'),
        ),
        migrations.AddField(
            model_name='restaurantbanner',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_restaurant_banner', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_category_category', to='restaurant.category'),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_category_dish', to='restaurant.dish'),
        ),
        migrations.AddField(
            model_name='dishbanner',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_dish_banner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dishbanner',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_dish_banner', to='restaurant.dish'),
        ),
        migrations.AddField(
            model_name='dishbanner',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_dish_banner', to='media_file.media'),
        ),
        migrations.AddField(
            model_name='dish',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_dish', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_dish', to='restaurant.restaurant'),
        ),
    ]
