# Generated by Django 3.1.3 on 2021-11-04 23:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20211104_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
