# Generated by Django 3.1.3 on 2021-10-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurantbanner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='code',
            field=models.SlugField(unique=True),
        ),
    ]
