# Generated by Django 3.1.3 on 2021-11-05 10:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='code',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
