# Generated by Django 3.1.3 on 2021-10-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20211030_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='serve_count',
            field=models.IntegerField(default=0),
        ),
    ]
