version: '3.8'
services:
    db:
        image: postgres:13.3-alpine
        restart: always
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=postgres
            - APP_DB_USER=se_db_user
            - APP_DB_PASS=se_db_secret
            - APP_DB_NAME=se_db
            - PGDATA=/Backend/postgresql/data
        container_name: postgres_db
        volumes:
        - .:/docker-entrypoint-initdb.d/
        ports:
        - "5432:5432"

volumes:
    db-data:
